# https://github.com/awesome-containers/static-bash
ARG STATIC_BASH_VERSION=5.2.15
ARG STATIC_BASH_IMAGE=ghcr.io/awesome-containers/static-bash

# https://github.com/awesome-containers/static-sed
ARG STATIC_SED_VERSION=4.9
ARG STATIC_SED_IMAGE=ghcr.io/awesome-containers/static-sed

# https://github.com/awesome-containers/alpine-build-essential
ARG BUILD_ESSENTIAL_VERSION=3.17
ARG BUILD_ESSENTIAL_IMAGE=ghcr.io/awesome-containers/alpine-build-essential


FROM $STATIC_BASH_IMAGE:$STATIC_BASH_VERSION-slim AS static-bash
FROM $STATIC_SED_IMAGE:$STATIC_SED_VERSION AS static-sed
FROM $BUILD_ESSENTIAL_IMAGE:$BUILD_ESSENTIAL_VERSION AS build

WORKDIR /src/sed
COPY --from=static-sed /bin/sed ./

RUN set -xeu; \
    upx --no-progress --no-color sed; \
    upx -t --no-progress --no-color sed; \
    chmod -cR 755 sed; \
    chown -cR 0:0 sed; \
    ! ldd sed && :; \
    ./sed --version

# slim static sed image
FROM static-bash
COPY --from=build /src/sed/sed /bin/sed
